added arch binary

diff --git a/component/Makefile b/component/Makefile
--- a/component/Makefile
+++ b/component/Makefile
@@ -1,11 +1,11 @@
 BINARY=component
 GOARCH32=386
 GOARCH64=amd64
-GOARCH=arm64
+GOARCHARM64=arm64
 VERSION=v0.0.1
 ENV GO111MODULE=on
 
-all: linux arm64 solaris darwin windows vet fmt fmtcheck errcheck golint
+all: linux solaris darwin windows vet fmt fmtcheck errcheck golint
 
 linux:
 	@echo
@@ -18,6 +18,13 @@ linux:
 	@rm ../linux_${GOARCH64}/${BINARY} && echo 'LINUX BINARY FOR amd64 ARCHITECTUR REMOVED SUCCESFULLY' || echo 'LINUX BINARY FOR amd64 ARCHITECTUR WERE NOT REMOVED'
 	@echo 'BUILDING LINUX BINARY FOR amd64 ARCHITECTURE'
 	@GOOS=linux GOARCH=${GOARCH64} go build -o ../linux_${GOARCH64}/${BINARY} \
+	-ldflags="-X main.Version=${VERSION}" &&  \
+        echo 'BUILD EXECUTED SUCCESSFULLY' || echo 'BUILD FAILED'
+
+	@echo
+	@rm ../linux_${GOARCHARM64}/${BINARY} && echo 'LINUX ARM BINARY FOR amd64 ARCHITECTUR REMOVED SUCCESFULLY' || echo 'LINUX ARM BINARY FOR amd64 ARCHITECTUR WERE NOT REMOVED'
+	@echo 'BUILDING LINUX ARM BINARY FOR amd64 ARCHITECTURE'
+	@GOOS=linux GOARCH=${GOARCHARM64} go build -o ../linux_${GOARCHARM64}/${BINARY} \
 	-ldflags="-X main.Version=${VERSION}" &&  \
         echo 'BUILD EXECUTED SUCCESSFULLY' || echo 'BUILD FAILED'
 
@@ -37,12 +44,11 @@ darwin:
 	-ldflags="-X main.Version=${VERSION}" &&  \
         echo 'BUILD EXECUTED SUCCESSFULLY' || echo 'BUILD FAILED'
 
-arm64:
 	@echo
-	@rm ../linux_${GOARCH}/${BINARY} && echo 'ARM BINARY FOR amd64 ARCHITECTUR REMOVED SUCCESFULLY' || echo 'ARM BINARY FOR amd64 ARCHITECTUR WERE NOT REMOVED'
-	@echo 'BUILDING ARM BINARY FOR amd64 ARCHITECTURE'
-	@GOOS=linux GOARCH=${GOARCH} go build -o ../linux_${GOARCH}/${BINARY} \
-	-ldflags="-X main.Version=${VERSION}" &&  \
+	@rm ../darwin_${GOARCHARM64}/${BINARY} && echo 'DARWIN ARM BINARY FOR amd64 ARCHITECTUR REMOVED SUCCESFULLY' || echo 'DARWIN ARM BINARY FOR amd64 ARCHITECTUR WERE NOT REMOVED'
+	@echo 'BUILDING DARWIN ARM BINARY FOR amd64 ARCHITECTURE'
+	@GOOS=darwin GOARCH=${GOARCHARM64} go build -o ../darwin_${GOARCHARM64}/${BINARY} \
+	-ldflags="-linkmode=internal -X main.Version=${VERSION}" &&  \
         echo 'BUILD EXECUTED SUCCESSFULLY' || echo 'BUILD FAILED'
 
 windows:
